run:
  skip-dirs:
    - ui/icon

linters:
  enable-all: true
  disable:
    - funlen
    - lll
    - varnamelen
    - gomnd
    - cyclop
    - exhaustivestruct
    - gochecknoglobals
    - goerr113
    - wsl
    - gocognit
    - nestif
    - nosnakecase
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - dupl
    - gocyclo
    - maintidx
    - goconst

linters-settings:
  revive:
    rules:
      - name: var-naming
        disabled: true
