name: Build

on: [push, pull_request]

jobs:
  build:
    name: ${{ fromJson(matrix.target).rid }}

    strategy:
      fail-fast: false

      matrix:
        target:
          - '{"goos":"windows","rid":"win-x64","os":"windows-latest"}'
          - '{"goos":"linux","rid":"linux-x64","os":"ubuntu-latest"}'
          - '{"goos":"darwin","rid":"osx-x64","os":"macos-12"}'

    runs-on: ${{ fromJson(matrix.target).os }}

    env:
      GOOS: ${{ fromJson(matrix.target).goos }}
      GOARCH: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'

      - name: Install Build Package
        run: |
          yarn install --frozen-lockfile
        shell: bash

      - name: Build Koi
        run: |
          yarn gulp ciBuild
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: koi-dist-${{ fromJson(matrix.target).rid }}-${{ github.sha }}
          path: build/dist/
