name: Deploy gopkg

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  gopkg:
    name: ${{ matrix.pkg }}

    strategy:
      fail-fast: false

      matrix:
        pkg:
          - core
          - sdk
          - app

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare tag
        id: tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          VERSION="${GITHUB_REF##refs/tags/}"
          echo "Found Tag: ${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Deploy gopkg
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.ACTIONS_DEPLOY_MODULE_KEY }}
          user_name: 'Il Harper'
          user_email: 'hi@ilharper.com'
          external_repository: koishi-desktop/${{ matrix.pkg }}
          publish_branch: master
          publish_dir: packages/${{ matrix.pkg }}
          enable_jekyll: true # Not to create .nojekyll since this is not a gh page
          commit_message: 'chore: publish ${{ steps.tag.outputs.version }}'
          tag_name: ${{ steps.tag.outputs.version }} # Wouldn't create if empty
          tag_message: Publish ${{ steps.tag.outputs.version }}
