name: Lint

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.target.rid }}

    strategy:
      fail-fast: false

      matrix:
        target:
          - goos: windows
            rid: win-x64
            os: windows-2022
          - goos: linux
            rid: linux-x64
            os: ubuntu-20.04
          - goos: darwin
            rid: osx-x64
            os: macos-12

    runs-on: ${{ matrix.target.os }}

    env:
      GOOS: ${{ matrix.target.goos }}
      GOARCH: amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Cache Build Caches
        uses: actions/cache@v3
        with:
          path: build/caches/
          key: koi-${{ runner.os }}-${{ hashFiles('config.ts') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: yarn

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ~1.19.0
          cache: true
          cache-dependency-path: config.ts

      - name: Install Build Package
        run: |
          yarn install --frozen-lockfile
        shell: bash

      - name: Lint
        run: |
          yarn gulp ciLint
        shell: bash
